In [1]:
from pathlib import Path

# ==============================
# PROJECT CONFIGURATION
# ==============================

PROJECT_DIR = Path("/home/manish/trading_project/stock_screener")

# Existing FYERS credentials
ROOT_DIR = Path("/home/manish/trading_project")

ENV_FILE = ROOT_DIR / ".env"
ACCESS_FILE = ROOT_DIR / "access.txt"

# Scanner condition
REFERENCE_PRICE = 500.0
RANGE_PERCENT = 5.0

LOWER_PRICE = REFERENCE_PRICE * (1 - RANGE_PERCENT / 100)
UPPER_PRICE = REFERENCE_PRICE * (1 + RANGE_PERCENT / 100)

print("Reference Price :", REFERENCE_PRICE)
print("Range           :", f"{LOWER_PRICE:.2f} - {UPPER_PRICE:.2f}")
print("Access File     :", ACCESS_FILE)

Reference Price : 500.0
Range           : 475.00 - 525.00
Access File     : /home/manish/trading_project/access.txt

In [2]:
from pathlib import Path

# ==============================
# PROJECT CONFIGURATION
# ==============================

PROJECT_DIR = Path("/home/manish/trading_project/stock_screener")

# Existing FYERS credentials
ROOT_DIR = Path("/home/manish/trading_project")

ENV_FILE = ROOT_DIR / ".env"
ACCESS_FILE = ROOT_DIR / "access.txt"

# Scanner condition
REFERENCE_PRICE = 500.0
RANGE_PERCENT = 5.0

LOWER_PRICE = REFERENCE_PRICE * (1 - RANGE_PERCENT / 100)
UPPER_PRICE = REFERENCE_PRICE * (1 + RANGE_PERCENT / 100)

print("Reference Price :", REFERENCE_PRICE)
print("Range           :", f"{LOWER_PRICE:.2f} - {UPPER_PRICE:.2f}")
print("Access File     :", ACCESS_FILE)

Reference Price : 500.0
Range           : 475.00 - 525.00
Access File     : /home/manish/trading_project/access.txt

In [3]:
# ==========================================
# CELL 2 — FYERS API CLIENT
# ==========================================

import os
from dotenv import load_dotenv
from fyers_apiv3 import fyersModel

# Load existing FYERS configuration
load_dotenv(ENV_FILE)

APP_ID = os.getenv("FYERS_APP_ID")

if not APP_ID:
    raise ValueError("FYERS_APP_ID not found in .env")

# Load existing access token
ACCESS_TOKEN = ACCESS_FILE.read_text().strip()

if not ACCESS_TOKEN:
    raise ValueError("FYERS access token is empty")

# Create FYERS API client
fyers = fyersModel.FyersModel(
    client_id=APP_ID,
    token=ACCESS_TOKEN,
    log_path=""
)

print("FYERS client created successfully.")
print("App ID:", APP_ID)
print("Access token: loaded")

FYERS client created successfully.
App ID: 4DK6EK1V8X-100
Access token: loaded

In [4]:
# Check existing FYERS configuration files
from pathlib import Path

print(".env exists:", ENV_FILE.exists())
print("access.txt exists:", ACCESS_FILE.exists())

if ENV_FILE.exists():
    print("\n.env contents (variable names only):")
    for line in ENV_FILE.read_text().splitlines():
        line = line.strip()
        if line and not line.startswith("#") and "=" in line:
            print(line.split("=", 1)[0].strip())

print("\naccess.txt:")
print("exists:", ACCESS_FILE.exists())
print("size:", ACCESS_FILE.stat().st_size if ACCESS_FILE.exists() else 0)

.env exists: True
access.txt exists: True

.env contents (variable names only):
FYERS_APP_ID
FYERS_SECRET_KEY
FYERS_REDIRECT_URI

access.txt:
exists: True
size: 652

In [5]:
# ==========================================
# CELL 3 — TEST LIVE LTP
# ==========================================

test_symbols = [
    "NSE:RELIANCE-EQ",
    "NSE:TCS-EQ",
    "NSE:INFY-EQ",
]

data = {
    "symbols": ",".join(test_symbols)
}

response = fyers.quotes(data=data)

print(response)

{'message': '', 'code': 200, 'd': [{'n': 'NSE:RELIANCE-EQ', 'v': {'ask': 1248, 'bid': 0, 'chp': 0.61, 'ch': 7.6, 'description': 'NSE:RELIANCE-EQ', 'exchange': 'NSE', 'fyToken': '10100000002885', 'high_price': 1252.8, 'low_price': 1238.9, 'lp': 1248, 'open_price': 1242, 'original_name': 'NSE:RELIANCE-EQ', 'prev_close_price': 1248, 'short_name': 'RELIANCE-EQ', 'spread': 0, 'symbol': 'NSE:RELIANCE-EQ', 'tt': '1790208000', 'volume': 8352048, 'atp': 1247.3, 'imbalance': 0, 'mkt_imbalance': 0, 'reference_price': 0, 'indicative_price': 0}, 's': 'ok'}, {'n': 'NSE:TCS-EQ', 'v': {'ask': 2089.6, 'bid': 0, 'chp': -0.73, 'ch': -15.4, 'description': 'NSE:TCS-EQ', 'exchange': 'NSE', 'fyToken': '101000000011536', 'high_price': 2104.2, 'low_price': 2077.6, 'lp': 2089.6, 'open_price': 2099, 'original_name': 'NSE:TCS-EQ', 'prev_close_price': 2089.6, 'short_name': 'TCS-EQ', 'spread': 0, 'symbol': 'NSE:TCS-EQ', 'tt': '1790208000', 'volume': 2228402, 'atp': 2087.81, 'imbalance': 0, 'mkt_imbalance': 0, 'reference_price': 0, 'indicative_price': 0}, 's': 'ok'}, {'n': 'NSE:INFY-EQ', 'v': {'ask': 1020.5, 'bid': 0, 'chp': -0.86, 'ch': -8.9, 'description': 'NSE:INFY-EQ', 'exchange': 'NSE', 'fyToken': '10100000001594', 'high_price': 1029.4, 'low_price': 1015.1, 'lp': 1020.5, 'open_price': 1021.8, 'original_name': 'NSE:INFY-EQ', 'prev_close_price': 1020.5, 'short_name': 'INFY-EQ', 'spread': 0, 'symbol': 'NSE:INFY-EQ', 'tt': '1790208000', 'volume': 5108734, 'atp': 1020.34, 'imbalance': 0, 'mkt_imbalance': 0, 'reference_price': 0, 'indicative_price': 0}, 's': 'ok'}], 's': 'ok'}

In [6]:
# ==========================================
# CELL 4 — MULTI PRICE LEVEL SCANNER
# ==========================================

import pandas as pd

# Price levels to scan
PRICE_LEVELS = [100, 500, 1000, 1500, 2000, 3000, 5000]

RANGE_PERCENT = 5.0

results = []

# Scan each reference price level
for reference_price in PRICE_LEVELS:

    lower_price = reference_price * (1 - RANGE_PERCENT / 100)
    upper_price = reference_price * (1 + RANGE_PERCENT / 100)

    # Check all stocks returned by FYERS
    for item in response["d"]:

        symbol = item["n"]
        quote = item["v"]

        ltp = quote.get("lp")

        if ltp is None:
            continue

        # Check whether LTP is within ±5% of reference price
        if lower_price <= ltp <= upper_price:

            distance_percent = (
                (ltp - reference_price) / reference_price
            ) * 100

            results.append({
                "Symbol": symbol,
                "LTP": ltp,
                "Reference": reference_price,
                "Range Low": round(lower_price, 2),
                "Range High": round(upper_price, 2),
                "Distance (%)": round(distance_percent, 2),
                "Change (%)": quote.get("chp"),
                "Volume": quote.get("volume")
            })

scanner_df = pd.DataFrame(results)

if scanner_df.empty:
    print("No stocks found near the selected price levels.")

else:
    scanner_df = scanner_df.sort_values(
        ["Reference", "Distance (%)"]
    ).reset_index(drop=True)

    display(scanner_df)

,Symbol,LTP,Reference,Range Low,Range High,Distance (%),Change (%),Volume
0,NSE:INFY-EQ,1020.5,1000,950.0,1050.0,2.05,-0.86,5108734
1,NSE:TCS-EQ,2089.6,2000,1900.0,2100.0,4.48,-0.73,2228402

In [7]:
# ==========================================
# CELL 5 — LOAD NSE EQUITY UNIVERSE
# ==========================================

import pandas as pd

SYMBOL_MASTER_URL = "https://public.fyers.in/sym_details/NSE_CM.csv"

# Read raw FYERS symbol master
cm = pd.read_csv(
    SYMBOL_MASTER_URL,
    header=None
)

print("Rows:", len(cm))
print("Columns:", len(cm.columns))

# FYERS NSE CM:
# Column 3  (index 2)  = Instrument Type
# Column 10 (index 9)  = Symbol / trading symbol format
# Column 14 (index 13) = Underlying symbol

equity_master = cm[
    cm[2] == 0
].copy()

# Keep only normal NSE equity (EQ)
equity_master = equity_master[
    equity_master[9].astype(str).str.endswith("-EQ")
].copy()

# Create FYERS symbols
equity_master["fyers_symbol"] = equity_master[9].astype(str)

# Underlying stock name
equity_master["stock"] = equity_master[13].astype(str)

equity_master = equity_master[
    ["stock", "fyers_symbol"]
].drop_duplicates()

equity_master = equity_master.sort_values("fyers_symbol").reset_index(drop=True)

print("\nNSE equity stocks:", len(equity_master))

display(equity_master.head(20))

Rows: 10013
Columns: 21

NSE equity stocks: 2319

         stock       fyers_symbol
0    20MICRONS   NSE:20MICRONS-EQ
1   21STCENMGM  NSE:21STCENMGM-EQ
2       360ONE      NSE:360ONE-EQ
3   3BBLACKBIO  NSE:3BBLACKBIO-EQ
4      3MINDIA     NSE:3MINDIA-EQ
5       3PLAND      NSE:3PLAND-EQ
6       5PAISA      NSE:5PAISA-EQ
7      63MOONS     NSE:63MOONS-EQ
8     A2ZINFRA    NSE:A2ZINFRA-EQ
9      AAATECH     NSE:AAATECH-EQ
10   AADHARHFC   NSE:AADHARHFC-EQ
11      AAKASH      NSE:AAKASH-EQ
12  AAREYDRUGS  NSE:AAREYDRUGS-EQ
13       AARON       NSE:AARON-EQ
14  AARTIDRUGS  NSE:AARTIDRUGS-EQ
15    AARTIIND    NSE:AARTIIND-EQ
16  AARTIPHARM  NSE:AARTIPHARM-EQ
17       AARVI       NSE:AARVI-EQ
18      AASTHA      NSE:AASTHA-EQ
19       AAVAS       NSE:AAVAS-EQ

In [8]:
# ==========================================
# CELL 6 — FETCH LTP FOR ALL NSE STOCKS
# ==========================================

import time
import pandas as pd

BATCH_SIZE = 50

quote_results = []

symbols = equity_master["fyers_symbol"].tolist()

print(f"Total stocks : {len(symbols)}")
print(f"Batch size   : {BATCH_SIZE}")
print(f"Total batches: {(len(symbols) + BATCH_SIZE - 1) // BATCH_SIZE}")

for start in range(0, len(symbols), BATCH_SIZE):

    batch = symbols[start:start + BATCH_SIZE]

    data = {
        "symbols": ",".join(batch)
    }

    try:
        response_batch = fyers.quotes(data=data)

        if response_batch.get("s") == "ok":

            for item in response_batch.get("d", []):

                if item.get("s") != "ok":
                    continue

                quote = item.get("v", {})

                quote_results.append({
                    "Symbol": item.get("n"),
                    "LTP": quote.get("lp"),
                    "Change (%)": quote.get("chp"),
                    "Volume": quote.get("volume"),
                    "High": quote.get("high_price"),
                    "Low": quote.get("low_price"),
                    "Open": quote.get("open_price"),
                    "Prev Close": quote.get("prev_close_price"),
                })

        else:
            print(
                f"Batch {start // BATCH_SIZE + 1} failed:",
                response_batch
            )

    except Exception as e:
        print(
            f"Batch {start // BATCH_SIZE + 1} error:",
            e
        )

    # Small pause between API requests
    time.sleep(0.2)

quote_df = pd.DataFrame(quote_results)

print("\n--------------------------------")
print("QUOTE SCAN COMPLETE")
print("--------------------------------")
print("Stocks received:", len(quote_df))

display(quote_df.head(20))

Total stocks : 2319
Batch size   : 50
Total batches: 47

--------------------------------
QUOTE SCAN COMPLETE
--------------------------------
Stocks received: 2319

,Symbol,LTP,Change (%),Volume,High,Low,Open,Prev Close
0,NSE:20MICRONS-EQ,219.21,1.28,104573,223.95,215.80,220.80,219.21
1,NSE:21STCENMGM-EQ,39.92,0.76,6072,39.95,39.01,39.94,39.92
2,NSE:360ONE-EQ,1108.00,3.21,3642452,1122.00,1082.40,1093.70,1108.00
3,NSE:3BBLACKBIO-EQ,1431.60,4.55,6553,1440.00,1391.10,1400.00,1431.60
4,NSE:3MINDIA-EQ,34615.00,1.15,4992,35000.00,34225.00,34225.00,34615.00
5,NSE:3PLAND-EQ,30.91,0.55,2691,31.05,30.35,30.75,30.91
6,NSE:5PAISA-EQ,318.15,0.90,30838,321.70,315.00,317.25,318.15
7,NSE:63MOONS-EQ,852.95,1.33,510000,873.20,831.65,849.80,852.95
8,NSE:A2ZINFRA-EQ,14.79,0.41,192304,15.19,14.65,14.73,14.79
9,NSE:AAATECH-EQ,93.56,-0.18,116561,94.90,90.20,94.00,93.56
10,NSE:AADHARHFC-EQ,454.55,-0.72,222625,462.40,451.00,457.80,454.55
11,NSE:AAKASH-EQ,9.13,1.90,102979,9.18,8.95,9.00,9.13
12,NSE:AAREYDRUGS-EQ,102.63,0.11,352115,103.90,100.85,102.37,102.63
13,NSE:AARON-EQ,122.60,1.76,7785,124.00,119.63,121.00,122.60
14,NSE:AARTIDRUGS-EQ,436.25,2.47,198653,443.50,428.00,428.95,436.25
15,NSE:AARTIIND-EQ,491.35,-0.94,402389,504.25,489.20,493.00,491.35
16,NSE:AARTIPHARM-EQ,940.10,6.38,2945650,957.30,885.00,885.00,940.10
17,NSE:AARVI-EQ,136.48,-1.23,8363,140.40,136.00,138.21,136.48
18,NSE:AASTHA-EQ,89.77,9.99,2984740,89.78,83.00,83.00,89.77
19,NSE:AAVAS-EQ,1285.80,-2.08,77904,1339.80,1280.30,1313.20,1285.80

In [9]:
# ==========================================
# CELL 7 — PRICE LEVEL ±5% SCANNER
# ==========================================

PRICE_LEVELS = [100, 500, 1000, 1500, 2000 ]
RANGE_PERCENT = 5.0

scanner_results = []

for reference_price in PRICE_LEVELS:

    lower_price = reference_price * (1 - RANGE_PERCENT / 100)
    upper_price = reference_price * (1 + RANGE_PERCENT / 100)

    matches = quote_df[
        (quote_df["LTP"] >= lower_price) &
        (quote_df["LTP"] <= upper_price)
    ].copy()

    if not matches.empty:

        matches["Reference"] = reference_price

        matches["Range"] = (
            f"₹{lower_price:.2f} - ₹{upper_price:.2f}"
        )

        matches["Distance (%)"] = (
            (matches["LTP"] - reference_price)
            / reference_price
            * 100
        ).round(2)

        scanner_results.append(matches)


if scanner_results:

    price_scanner_df = pd.concat(
        scanner_results,
        ignore_index=True
    )

    price_scanner_df = price_scanner_df[
        [
            "Symbol",
            "LTP",
            "Reference",
            "Range",
            "Distance (%)",
            "Change (%)",
            "Volume"
        ]
    ]

    price_scanner_df = price_scanner_df.sort_values(
        ["Reference", "Distance (%)"]
    ).reset_index(drop=True)

    # Add serial number
    price_scanner_df.insert(
        0,
        "No.",
        range(1, len(price_scanner_df) + 1)
    )

    # Display complete list only once
    pd.set_option("display.max_rows", None)
    pd.set_option("display.max_columns", None)

    print(
        f"Stocks found within ±{RANGE_PERCENT}% "
        f"of selected price levels: "
        f"{len(price_scanner_df)}"
    )

    display(price_scanner_df)

else:

    print("No stocks found near the selected price levels.")

Stocks found within ±5.0% of selected price levels: 200

,No.,Symbol,LTP,Reference,Range,Distance (%),Change (%),Volume
0,1,NSE:VASUPRADA-EQ,95.05,100,₹95.00 - ₹105.00,-4.95,-4.95,31
1,2,NSE:UMIYA-MRO-EQ,95.10,100,₹95.00 - ₹105.00,-4.90,-2.25,11302
2,3,NSE:ANDHRSUGAR-EQ,95.20,100,₹95.00 - ₹105.00,-4.80,-0.16,213868
3,4,NSE:NTPCGREEN-EQ,95.42,100,₹95.00 - ₹105.00,-4.58,2.26,5223366
4,5,NSE:APCL-EQ,95.93,100,₹95.00 - ₹105.00,-4.07,1.19,2451
5,6,NSE:VISAKAIND-EQ,96.08,100,₹95.00 - ₹105.00,-3.92,1.70,149545
6,7,NSE:PREMIERPOL-EQ,96.72,100,₹95.00 - ₹105.00,-3.28,19.38,6517058
7,8,NSE:JAICORPLTD-EQ,96.73,100,₹95.00 - ₹105.00,-3.27,2.63,498373
8,9,NSE:AVTNPL-EQ,96.88,100,₹95.00 - ₹105.00,-3.12,-1.40,1064371
9,10,NSE:WCIL-EQ,97.33,100,₹95.00 - ₹105.00,-2.67,2.30,183868
10,11,NSE:ADSL-EQ,97.78,100,₹95.00 - ₹105.00,-2.22,1.39,76698
11,12,NSE:AGRITECH-EQ,97.83,100,₹95.00 - ₹105.00,-2.17,0.46,1258
12,13,NSE:GNRL-EQ,98.07,100,₹95.00 - ₹105.00,-1.93,-0.36,1665342
13,14,NSE:GMRP&UI-EQ,98.13,100,₹95.00 - ₹105.00,-1.87,3.01,3658751
14,15,NSE:PDMJEPAPER-EQ,98.27,100,₹95.00 - ₹105.00,-1.73,0.93,130398
15,16,NSE:HEROMOTORS-EQ,98.40,100,₹95.00 - ₹105.00,-1.60,17.14,139842838
16,17,NSE:CAMLINFINE-EQ,98.69,100,₹95.00 - ₹105.00,-1.31,2.32,1115122
17,18,NSE:PVSL-EQ,98.71,100,₹95.00 - ₹105.00,-1.29,-1.21,56036
18,19,NSE:GMRAIRPORT-EQ,99.14,100,₹95.00 - ₹105.00,-0.86,0.80,12088650
19,20,NSE:HRYNSHP-EQ,99.52,100,₹95.00 - ₹105.00,-0.48,-0.33,332
20,21,NSE:REMSONSIND-EQ,99.87,100,₹95.00 - ₹105.00,-0.13,2.10,332855
21,22,NSE:PIGL-EQ,99.92,100,₹95.00 - ₹105.00,-0.08,-1.13,19603
22,23,NSE:INDORAMA-EQ,100.00,100,₹95.00 - ₹105.00,0.00,-3.45,1969705
23,24,NSE:SARLAPOLY-EQ,100.03,100,₹95.00 - ₹105.00,0.03,0.78,66846
24,25,NSE:ANSALBU-EQ,100.14,100,₹95.00 - ₹105.00,0.14,11.12,179538
25,26,NSE:ENIL-EQ,100.17,100,₹95.00 - ₹105.00,0.17,0.53,2106
26,27,NSE:JKIPL-EQ,100.25,100,₹95.00 - ₹105.00,0.25,1.02,3606
27,28,NSE:MAHEPC-EQ,100.45,100,₹95.00 - ₹105.00,0.45,1.72,18962
28,29,NSE:ATLASCYCLE-EQ,100.46,100,₹95.00 - ₹105.00,0.46,7.39,239595
29,30,NSE:DBREALTY-EQ,101.48,100,₹95.00 - ₹105.00,1.48,5.00,1033102
30,31,NSE:ALKALI-EQ,101.63,100,₹95.00 - ₹105.00,1.63,-1.52,169113
31,32,NSE:SAMBANDAM-EQ,102.50,100,₹95.00 - ₹105.00,2.50,1.49,1229
32,33,NSE:AAREYDRUGS-EQ,102.63,100,₹95.00 - ₹105.00,2.63,0.11,352115
33,34,NSE:CSM-EQ,103.93,100,₹95.00 - ₹105.00,3.93,-1.16,288893
34,35,NSE:MAANALU-EQ,103.93,100,₹95.00 - ₹105.00,3.93,-0.84,177522
35,36,NSE:BEDMUTHA-EQ,104.89,100,₹95.00 - ₹105.00,4.89,2.26,5964
36,37,NSE:GILLANDERS-EQ,104.91,100,₹95.00 - ₹105.00,4.91,-0.09,4202
37,38,NSE:BORORENEW-EQ,475.00,500,₹475.00 - ₹525.00,-5.00,0.06,244086
38,39,NSE:FERMENTA-EQ,475.50,500,₹475.00 - ₹525.00,-4.90,1.04,69810
39,40,NSE:TECHNOCRAF-EQ,475.65,500,₹475.00 - ₹525.00,-4.87,3.97,2956605
40,41,NSE:ICIL-EQ,476.55,500,₹475.00 - ₹525.00,-4.69,6.16,1924680
41,42,NSE:SHAKTIPUMP-EQ,476.80,500,₹475.00 - ₹525.00,-4.64,1.64,331661
42,43,NSE:DYCL-EQ,476.90,500,₹475.00 - ₹525.00,-4.62,5.10,762315
43,44,NSE:KKCL-EQ,477.55,500,₹475.00 - ₹525.00,-4.49,-1.50,15632
44,45,NSE:KIRLFER-EQ,478.10,500,₹475.00 - ₹525.00,-4.38,-0.36,126883
45,46,NSE:POONAWALLA-EQ,478.85,500,₹475.00 - ₹525.00,-4.23,1.47,1880797
46,47,NSE:JKIL-EQ,479.60,500,₹475.00 - ₹525.00,-4.08,0.33,27434
47,48,NSE:PANAMAPET-EQ,480.70,500,₹475.00 - ₹525.00,-3.86,-0.11,164568
48,49,NSE:SMSPHARMA-EQ,482.95,500,₹475.00 - ₹525.00,-3.41,-0.08,801318
49,50,NSE:RAJRATAN-EQ,483.20,500,₹475.00 - ₹525.00,-3.36,7.33,618194
50,51,NSE:JUBLFOOD-EQ,483.30,500,₹475.00 - ₹525.00,-3.34,-1.59,625258
51,52,NSE:ICICIPRULI-EQ,484.50,500,₹475.00 - ₹525.00,-3.10,-0.44,750732
52,53,NSE:HONASA-EQ,484.90,500,₹475.00 - ₹525.00,-3.02,2.38,712921
53,54,NSE:SUPRAJIT-EQ,485.05,500,₹475.00 - ₹525.00,-2.99,0.33,28891
54,55,NSE:PML-EQ,486.00,500,₹475.00 - ₹525.00,-2.80,-2.58,1239
55,56,NSE:POCL-EQ,487.40,500,₹475.00 - ₹525.00,-2.52,3.06,365156
56,57,NSE:GSPCROP-EQ,488.85,500,₹475.00 - ₹525.00,-2.23,0.81,242198
57,58,NSE:TRANSRAILL-EQ,488.90,500,₹475.00 - ₹525.00,-2.22,2.46,10396978
58,59,NSE:ASIANENE-EQ,489.70,500,₹475.00 - ₹525.00,-2.06,0.02,308700
59,60,NSE:RUBYMILLS-EQ,490.20,500,₹475.00 - ₹525.00,-1.96,6.58,111992
60,61,NSE:SUNTV-EQ,490.20,500,₹475.00 - ₹525.00,-1.96,0.02,1771617
61,62,NSE:AARTIIND-EQ,491.35,500,₹475.00 - ₹525.00,-1.73,-0.94,402389
62,63,NSE:SOFTTECH-EQ,491.85,500,₹475.00 - ₹525.00,-1.63,-1.28,3096
63,64,NSE:AGARWALEYE-EQ,494.80,500,₹475.00 - ₹525.00,-1.04,0.35,329131
64,65,NSE:SHREEPUSHK-EQ,495.80,500,₹475.00 - ₹525.00,-0.84,-1.99,50695
65,66,NSE:PRECWIRE-EQ,498.85,500,₹475.00 - ₹525.00,-0.23,1.58,715914
66,67,NSE:HEXT-EQ,500.00,500,₹475.00 - ₹525.00,0.00,-0.83,124075
67,68,NSE:TANLA-EQ,500.40,500,₹475.00 - ₹525.00,0.08,3.10,473046
68,69,NSE:WHBRADY-EQ,502.60,500,₹475.00 - ₹525.00,0.52,8.23,232
69,70,NSE:NEWGEN-EQ,504.15,500,₹475.00 - ₹525.00,0.83,1.70,688103
70,71,NSE:CMLL-EQ,504.65,500,₹475.00 - ₹525.00,0.93,2.80,514379
71,72,NSE:TCIEXP-EQ,505.60,500,₹475.00 - ₹525.00,1.12,4.00,22609
72,73,NSE:BAJAJCON-EQ,505.85,500,₹475.00 - ₹525.00,1.17,-1.54,599193
73,74,NSE:SARDAEN-EQ,505.95,500,₹475.00 - ₹525.00,1.19,0.52,159141
74,75,NSE:BALUFORGE-EQ,506.25,500,₹475.00 - ₹525.00,1.25,0.20,631352
75,76,NSE:SANATHAN-EQ,506.35,500,₹475.00 - ₹525.00,1.27,7.44,484976
76,77,NSE:LANDMARK-EQ,506.40,500,₹475.00 - ₹525.00,1.28,-0.80,57410
77,78,NSE:SAREGAMA-EQ,507.00,500,₹475.00 - ₹525.00,1.40,0.73,438443
78,79,NSE:MAGADSUGAR-EQ,509.20,500,₹475.00 - ₹525.00,1.84,1.69,16374
79,80,NSE:SAIPARENT-EQ,509.30,500,₹475.00 - ₹525.00,1.86,0.52,62456
80,81,NSE:AMRUTANJAN-EQ,510.05,500,₹475.00 - ₹525.00,2.01,2.00,34784
81,82,NSE:WONDERLA-EQ,510.75,500,₹475.00 - ₹525.00,2.15,-0.08,26910
82,83,NSE:ARSSBL-EQ,510.80,500,₹475.00 - ₹525.00,2.16,2.93,413000
83,84,NSE:JKLAKSHMI-EQ,511.20,500,₹475.00 - ₹525.00,2.24,0.67,46467
84,85,NSE:HINDCOPPER-EQ,513.00,500,₹475.00 - ₹525.00,2.60,0.94,6140632
85,86,NSE:SHIVAUM-EQ,513.20,500,₹475.00 - ₹525.00,2.64,-0.36,9201
86,87,NSE:VOEPL-EQ,515.10,500,₹475.00 - ₹525.00,3.02,4.47,79459
87,88,NSE:KLBRENG-B-EQ,518.60,500,₹475.00 - ₹525.00,3.72,-0.17,500546
88,89,NSE:TENNIND-EQ,518.60,500,₹475.00 - ₹525.00,3.72,-2.66,986500
89,90,NSE:AEROFLEX-EQ,520.80,500,₹475.00 - ₹525.00,4.16,0.79,939383
90,91,NSE:JSWENERGY-EQ,521.00,500,₹475.00 - ₹525.00,4.20,0.58,1923195
91,92,NSE:PGEL-EQ,521.15,500,₹475.00 - ₹525.00,4.23,0.18,546381
92,93,NSE:RENTOMOJO-EQ,521.35,500,₹475.00 - ₹525.00,4.27,-0.68,7882264
93,94,NSE:TEJASNET-EQ,521.55,500,₹475.00 - ₹525.00,4.31,1.02,890300
94,95,NSE:APOLLOPIPE-EQ,522.45,500,₹475.00 - ₹525.00,4.49,-0.69,69429
95,96,NSE:JSLL-EQ,524.30,500,₹475.00 - ₹525.00,4.86,1.73,426083
96,97,NSE:JENBURPH-EQ,952.00,1000,₹950.00 - ₹1050.00,-4.80,-0.54,2772
97,98,NSE:INDUSINDBK-EQ,959.30,1000,₹950.00 - ₹1050.00,-4.07,0.45,2626452
98,99,NSE:EXCELINDUS-EQ,963.30,1000,₹950.00 - ₹1050.00,-3.67,1.12,8868
99,100,NSE:CYIENTDLM-EQ,963.50,1000,₹950.00 - ₹1050.00,-3.65,5.05,523966
100,101,NSE:GMBREW-EQ,968.30,1000,₹950.00 - ₹1050.00,-3.17,2.14,49050
101,102,NSE:ASAHIINDIA-EQ,971.30,1000,₹950.00 - ₹1050.00,-2.87,0.64,262585
102,103,NSE:SHARDAMOTR-EQ,971.85,1000,₹950.00 - ₹1050.00,-2.81,-1.41,161127
103,104,NSE:MALLCOM-EQ,975.35,1000,₹950.00 - ₹1050.00,-2.46,2.49,3973
104,105,NSE:JPOLYINVST-EQ,978.95,1000,₹950.00 - ₹1050.00,-2.10,0.64,1063
105,106,NSE:DCMSHRIRAM-EQ,980.00,1000,₹950.00 - ₹1050.00,-2.00,0.07,25367
106,107,NSE:DHANUKA-EQ,982.65,1000,₹950.00 - ₹1050.00,-1.74,1.68,30647
107,108,NSE:MANINDS-EQ,986.70,1000,₹950.00 - ₹1050.00,-1.33,16.10,10691371
108,109,NSE:SPAL-EQ,989.50,1000,₹950.00 - ₹1050.00,-1.05,1.00,26317
109,110,NSE:MIDWESTLTD-EQ,993.40,1000,₹950.00 - ₹1050.00,-0.66,-2.45,29595
110,111,NSE:SBIN-EQ,994.10,1000,₹950.00 - ₹1050.00,-0.59,0.72,4522248
111,112,NSE:TATACONSUM-EQ,994.30,1000,₹950.00 - ₹1050.00,-0.57,1.04,850774
112,113,NSE:GANDHITUBE-EQ,995.05,1000,₹950.00 - ₹1050.00,-0.50,-0.81,27224
113,114,NSE:KSL-EQ,998.25,1000,₹950.00 - ₹1050.00,-0.18,4.08,646949
114,115,NSE:SUPRIYA-EQ,1000.90,1000,₹950.00 - ₹1050.00,0.09,6.58,1007970
115,116,NSE:DHUNINV-EQ,1001.75,1000,₹950.00 - ₹1050.00,0.18,1.85,423
116,117,NSE:HINDALCO-EQ,1003.80,1000,₹950.00 - ₹1050.00,0.38,3.17,5158521
117,118,NSE:TINNARUBR-EQ,1007.25,1000,₹950.00 - ₹1050.00,0.73,-0.08,27984
118,119,NSE:THACKER-EQ,1008.00,1000,₹950.00 - ₹1050.00,0.80,-0.07,18
119,120,NSE:MAITHANALL-EQ,1009.90,1000,₹950.00 - ₹1050.00,0.99,1.50,111790
120,121,NSE:SHRIRAMFIN-EQ,1010.80,1000,₹950.00 - ₹1050.00,1.08,0.48,2916356
121,122,NSE:TECHNOE-EQ,1012.05,1000,₹950.00 - ₹1050.00,1.20,0.64,71021
122,123,NSE:DREDGECORP-EQ,1017.50,1000,₹950.00 - ₹1050.00,1.75,2.38,53819
123,124,NSE:INFY-EQ,1020.50,1000,₹950.00 - ₹1050.00,2.05,-0.86,5108734
124,125,NSE:NELCO-EQ,1020.75,1000,₹950.00 - ₹1050.00,2.08,0.89,511625
125,126,NSE:ABSLAMC-EQ,1026.60,1000,₹950.00 - ₹1050.00,2.66,-0.04,65947
126,127,NSE:SANDESH-EQ,1027.00,1000,₹950.00 - ₹1050.00,2.70,-1.13,644
127,128,NSE:DSSL-EQ,1030.40,1000,₹950.00 - ₹1050.00,3.04,0.80,16469
128,129,NSE:KRISHNADEF-EQ,1032.90,1000,₹950.00 - ₹1050.00,3.29,0.71,66368
129,130,NSE:MANGLMCEM-EQ,1033.30,1000,₹950.00 - ₹1050.00,3.33,2.68,69168
130,131,NSE:BIL-EQ,1034.95,1000,₹950.00 - ₹1050.00,3.50,-1.48,4569
131,132,NSE:GANECOS-EQ,1036.60,1000,₹950.00 - ₹1050.00,3.66,3.83,48904
132,133,NSE:SHILPAMED-EQ,1037.70,1000,₹950.00 - ₹1050.00,3.77,0.44,613628
133,134,NSE:MOTILALOFS-EQ,1042.50,1000,₹950.00 - ₹1050.00,4.25,3.53,2096581
134,135,NSE:BAJFINANCE-EQ,1043.20,1000,₹950.00 - ₹1050.00,4.32,3.41,8618523
135,136,NSE:CCL-EQ,1043.20,1000,₹950.00 - ₹1050.00,4.32,-0.65,235839
136,137,NSE:KSHINTL-EQ,1046.80,1000,₹950.00 - ₹1050.00,4.68,0.56,224075
137,138,NSE:DODLA-EQ,1048.60,1000,₹950.00 - ₹1050.00,4.86,0.10,19425
138,139,NSE:GABRIEL-EQ,1428.10,1500,₹1425.00 - ₹1575.00,-4.79,-2.94,1533195
139,140,NSE:3BBLACKBIO-EQ,1431.60,1500,₹1425.00 - ₹1575.00,-4.56,4.55,6553
140,141,NSE:GMMPFAUDLR-EQ,1432.60,1500,₹1425.00 - ₹1575.00,-4.49,-2.03,245810
141,142,NSE:NILE-EQ,1436.60,1500,₹1425.00 - ₹1575.00,-4.23,-0.57,1589
142,143,NSE:VOITHPAPR-EQ,1440.00,1500,₹1425.00 - ₹1575.00,-4.00,0.00,619
143,144,NSE:UNITDSPR-EQ,1441.00,1500,₹1425.00 - ₹1575.00,-3.93,3.08,767514
144,145,NSE:ROSSTECH-EQ,1449.80,1500,₹1425.00 - ₹1575.00,-3.35,-2.96,276498
145,146,NSE:BBTC-EQ,1450.20,1500,₹1425.00 - ₹1575.00,-3.32,-0.70,48883
146,147,NSE:DPABHUSHAN-EQ,1455.90,1500,₹1425.00 - ₹1575.00,-2.94,-0.92,23394
147,148,NSE:CLEANMAX-EQ,1457.50,1500,₹1425.00 - ₹1575.00,-2.83,6.58,1550273
148,149,NSE:FINCABLES-EQ,1470.20,1500,₹1425.00 - ₹1575.00,-1.99,0.14,594101
149,150,NSE:CHOLAHLDNG-EQ,1472.40,1500,₹1425.00 - ₹1575.00,-1.84,0.88,233988
150,151,NSE:GESHIP-EQ,1483.80,1500,₹1425.00 - ₹1575.00,-1.08,1.49,411769
151,152,NSE:PRESTIGE-EQ,1490.00,1500,₹1425.00 - ₹1575.00,-0.67,0.70,141420
152,153,NSE:SAFARI-EQ,1491.60,1500,₹1425.00 - ₹1575.00,-0.56,-0.46,42901
153,154,NSE:MEDANTA-EQ,1496.10,1500,₹1425.00 - ₹1575.00,-0.26,0.56,78256
154,155,NSE:ATHERENERG-EQ,1499.40,1500,₹1425.00 - ₹1575.00,-0.04,-2.88,6687076
155,156,NSE:UPHOT-EQ,1500.00,1500,₹1425.00 - ₹1575.00,0.00,-0.52,29
156,157,NSE:ICICIGI-EQ,1500.60,1500,₹1425.00 - ₹1575.00,0.04,1.39,708998
157,158,NSE:UNIVCABLES-EQ,1508.80,1500,₹1425.00 - ₹1575.00,0.59,2.07,62316
158,159,NSE:HALEOSLABS-EQ,1510.70,1500,₹1425.00 - ₹1575.00,0.71,0.71,1188
159,160,NSE:SKFINDIA-EQ,1519.80,1500,₹1425.00 - ₹1575.00,1.32,0.84,36312
160,161,NSE:BHARTIHEXA-EQ,1525.20,1500,₹1425.00 - ₹1575.00,1.68,-0.59,69109
161,162,NSE:BLUESTARCO-EQ,1532.60,1500,₹1425.00 - ₹1575.00,2.17,0.50,110416
162,163,NSE:BPLPHARMA-EQ,1545.50,1500,₹1425.00 - ₹1575.00,3.03,0.90,2199
163,164,NSE:QPOWER-EQ,1555.60,1500,₹1425.00 - ₹1575.00,3.71,4.29,326604
164,165,NSE:TECHM-EQ,1557.00,1500,₹1425.00 - ₹1575.00,3.80,0.35,851068
165,166,NSE:CONCORDBIO-EQ,1560.30,1500,₹1425.00 - ₹1575.00,4.02,1.82,147508
166,167,NSE:GRAVITA-EQ,1561.10,1500,₹1425.00 - ₹1575.00,4.07,-0.24,358210
167,168,NSE:MFSL-EQ,1562.90,1500,₹1425.00 - ₹1575.00,4.19,0.56,324133
168,169,NSE:VIJAYA-EQ,1570.70,1500,₹1425.00 - ₹1575.00,4.71,3.61,209302
169,170,NSE:MASTEK-EQ,1573.30,1500,₹1425.00 - ₹1575.00,4.89,0.34,54954
170,171,NSE:NH-EQ,1919.30,2000,₹1900.00 - ₹2100.00,-4.04,1.91,104223
171,172,NSE:ECLERX-EQ,1924.20,2000,₹1900.00 - ₹2100.00,-3.79,0.01,60071
172,173,NSE:LALPATHLAB-EQ,1924.30,2000,₹1900.00 - ₹2100.00,-3.79,0.76,230347
173,174,NSE:FIEMIND-EQ,1924.50,2000,₹1900.00 - ₹2100.00,-3.78,0.93,67467
174,175,NSE:MANORAMA-EQ,1929.40,2000,₹1900.00 - ₹2100.00,-3.53,0.96,141711
175,176,NSE:HONDAPOWER-EQ,1931.70,2000,₹1900.00 - ₹2100.00,-3.41,0.79,1632
176,177,NSE:IKS-EQ,1937.80,2000,₹1900.00 - ₹2100.00,-3.11,3.67,1011998
177,178,NSE:AXISCADES-EQ,1940.20,2000,₹1900.00 - ₹2100.00,-2.99,2.60,291136
178,179,NSE:NBIFIN-EQ,1948.90,2000,₹1900.00 - ₹2100.00,-2.55,0.05,5488
179,180,NSE:HINDUNILVR-EQ,1950.00,2000,₹1900.00 - ₹2100.00,-2.50,0.84,870342
180,181,NSE:COROMANDEL-EQ,1956.00,2000,₹1900.00 - ₹2100.00,-2.20,0.57,144853
181,182,NSE:IPCALAB-EQ,1962.60,2000,₹1900.00 - ₹2100.00,-1.87,-1.50,159445
182,183,NSE:ARMANFIN-EQ,1968.90,2000,₹1900.00 - ₹2100.00,-1.55,-0.30,12730
183,184,NSE:ADVAIT-EQ,1976.80,2000,₹1900.00 - ₹2100.00,-1.16,-1.44,35052
184,185,NSE:GRINDWELL-EQ,1977.60,2000,₹1900.00 - ₹2100.00,-1.12,1.84,22292
185,186,NSE:EMCURE-EQ,1981.70,2000,₹1900.00 - ₹2100.00,-0.91,0.34,37562
186,187,NSE:PHOENIXLTD-EQ,1993.20,2000,₹1900.00 - ₹2100.00,-0.34,2.04,639296
187,188,NSE:GRPLTD-EQ,2001.20,2000,₹1900.00 - ₹2100.00,0.06,0.06,244
188,189,NSE:GODFRYPHLP-EQ,2003.00,2000,₹1900.00 - ₹2100.00,0.15,1.68,144961
189,190,NSE:BHARATFORG-EQ,2004.00,2000,₹1900.00 - ₹2100.00,0.20,-0.25,759299
190,191,NSE:NOVARTIND-EQ,2027.40,2000,₹1900.00 - ₹2100.00,1.37,2.74,77712
191,192,NSE:LAURUSLABS-EQ,2034.00,2000,₹1900.00 - ₹2100.00,1.70,1.37,1363988
192,193,NSE:LUMAXTECH-EQ,2044.90,2000,₹1900.00 - ₹2100.00,2.25,-3.38,280450
193,194,NSE:WABAG-EQ,2048.70,2000,₹1900.00 - ₹2100.00,2.43,-1.13,380343
194,195,NSE:MACPOWER-EQ,2059.50,2000,₹1900.00 - ₹2100.00,2.97,-1.76,43775
195,196,NSE:TEGA-EQ,2078.80,2000,₹1900.00 - ₹2100.00,3.94,0.47,671454
196,197,NSE:TCS-EQ,2089.60,2000,₹1900.00 - ₹2100.00,4.48,-0.73,2228402
197,198,NSE:HYUNDAI-EQ,2095.00,2000,₹1900.00 - ₹2100.00,4.75,-0.29,358724
198,199,NSE:BEML-EQ,2095.40,2000,₹1900.00 - ₹2100.00,4.77,-0.07,204095
199,200,NSE:HAPPYFORGE-EQ,2099.80,2000,₹1900.00 - ₹2100.00,4.99,-0.41,82497

In [10]:
# ==========================================
# CELL 7 — PRICE LEVEL ±5% SCANNER + CSV
# ==========================================

PRICE_LEVELS = [100, 500, 1000, 2000]
RANGE_PERCENT = 5.0

scanner_results = []

for reference_price in PRICE_LEVELS:

    lower_price = reference_price * (1 - RANGE_PERCENT / 100)
    upper_price = reference_price * (1 + RANGE_PERCENT / 100)

    matches = quote_df[
        (quote_df["LTP"] >= lower_price) &
        (quote_df["LTP"] <= upper_price)
    ].copy()

    if not matches.empty:

        matches["Reference"] = reference_price

        matches["Range"] = (
            f"₹{lower_price:.2f} - ₹{upper_price:.2f}"
        )

        matches["Distance (%)"] = (
            (matches["LTP"] - reference_price)
            / reference_price
            * 100
        ).round(2)

        scanner_results.append(matches)


if scanner_results:

    price_scanner_df = pd.concat(
        scanner_results,
        ignore_index=True
    )

    price_scanner_df = price_scanner_df[
        [
            "Symbol",
            "LTP",
            "Reference",
            "Range",
            "Distance (%)",
            "Change (%)",
            "Volume"
        ]
    ]

    price_scanner_df = price_scanner_df.sort_values(
        ["Reference", "Distance (%)"]
    ).reset_index(drop=True)

    # Add serial number
    price_scanner_df.insert(
        0,
        "No.",
        range(1, len(price_scanner_df) + 1)
    )

    # Display complete result
    pd.set_option("display.max_rows", None)
    pd.set_option("display.max_columns", None)

    print(
        f"Stocks found within ±{RANGE_PERCENT}% "
        f"of selected price levels: "
        f"{len(price_scanner_df)}"
    )

    display(price_scanner_df)

    # --------------------------------------
    # SAVE RESULT TO CSV
    # --------------------------------------

    CSV_PATH = PROJECT_DIR / "notebooks" / "price_scanner_results.csv"

    price_scanner_df.to_csv(
        CSV_PATH,
        index=False
    )

    print("\nCSV saved successfully:")
    print(CSV_PATH)

else:

    print("No stocks found near the selected price levels.")

Stocks found within ±5.0% of selected price levels: 168

,No.,Symbol,LTP,Reference,Range,Distance (%),Change (%),Volume
0,1,NSE:VASUPRADA-EQ,95.05,100,₹95.00 - ₹105.00,-4.95,-4.95,31
1,2,NSE:UMIYA-MRO-EQ,95.10,100,₹95.00 - ₹105.00,-4.90,-2.25,11302
2,3,NSE:ANDHRSUGAR-EQ,95.20,100,₹95.00 - ₹105.00,-4.80,-0.16,213868
3,4,NSE:NTPCGREEN-EQ,95.42,100,₹95.00 - ₹105.00,-4.58,2.26,5223366
4,5,NSE:APCL-EQ,95.93,100,₹95.00 - ₹105.00,-4.07,1.19,2451
5,6,NSE:VISAKAIND-EQ,96.08,100,₹95.00 - ₹105.00,-3.92,1.70,149545
6,7,NSE:PREMIERPOL-EQ,96.72,100,₹95.00 - ₹105.00,-3.28,19.38,6517058
7,8,NSE:JAICORPLTD-EQ,96.73,100,₹95.00 - ₹105.00,-3.27,2.63,498373
8,9,NSE:AVTNPL-EQ,96.88,100,₹95.00 - ₹105.00,-3.12,-1.40,1064371
9,10,NSE:WCIL-EQ,97.33,100,₹95.00 - ₹105.00,-2.67,2.30,183868
10,11,NSE:ADSL-EQ,97.78,100,₹95.00 - ₹105.00,-2.22,1.39,76698
11,12,NSE:AGRITECH-EQ,97.83,100,₹95.00 - ₹105.00,-2.17,0.46,1258
12,13,NSE:GNRL-EQ,98.07,100,₹95.00 - ₹105.00,-1.93,-0.36,1665342
13,14,NSE:GMRP&UI-EQ,98.13,100,₹95.00 - ₹105.00,-1.87,3.01,3658751
14,15,NSE:PDMJEPAPER-EQ,98.27,100,₹95.00 - ₹105.00,-1.73,0.93,130398
15,16,NSE:HEROMOTORS-EQ,98.40,100,₹95.00 - ₹105.00,-1.60,17.14,139842838
16,17,NSE:CAMLINFINE-EQ,98.69,100,₹95.00 - ₹105.00,-1.31,2.32,1115122
17,18,NSE:PVSL-EQ,98.71,100,₹95.00 - ₹105.00,-1.29,-1.21,56036
18,19,NSE:GMRAIRPORT-EQ,99.14,100,₹95.00 - ₹105.00,-0.86,0.80,12088650
19,20,NSE:HRYNSHP-EQ,99.52,100,₹95.00 - ₹105.00,-0.48,-0.33,332
20,21,NSE:REMSONSIND-EQ,99.87,100,₹95.00 - ₹105.00,-0.13,2.10,332855
21,22,NSE:PIGL-EQ,99.92,100,₹95.00 - ₹105.00,-0.08,-1.13,19603
22,23,NSE:INDORAMA-EQ,100.00,100,₹95.00 - ₹105.00,0.00,-3.45,1969705
23,24,NSE:SARLAPOLY-EQ,100.03,100,₹95.00 - ₹105.00,0.03,0.78,66846
24,25,NSE:ANSALBU-EQ,100.14,100,₹95.00 - ₹105.00,0.14,11.12,179538
25,26,NSE:ENIL-EQ,100.17,100,₹95.00 - ₹105.00,0.17,0.53,2106
26,27,NSE:JKIPL-EQ,100.25,100,₹95.00 - ₹105.00,0.25,1.02,3606
27,28,NSE:MAHEPC-EQ,100.45,100,₹95.00 - ₹105.00,0.45,1.72,18962
28,29,NSE:ATLASCYCLE-EQ,100.46,100,₹95.00 - ₹105.00,0.46,7.39,239595
29,30,NSE:DBREALTY-EQ,101.48,100,₹95.00 - ₹105.00,1.48,5.00,1033102
30,31,NSE:ALKALI-EQ,101.63,100,₹95.00 - ₹105.00,1.63,-1.52,169113
31,32,NSE:SAMBANDAM-EQ,102.50,100,₹95.00 - ₹105.00,2.50,1.49,1229
32,33,NSE:AAREYDRUGS-EQ,102.63,100,₹95.00 - ₹105.00,2.63,0.11,352115
33,34,NSE:CSM-EQ,103.93,100,₹95.00 - ₹105.00,3.93,-1.16,288893
34,35,NSE:MAANALU-EQ,103.93,100,₹95.00 - ₹105.00,3.93,-0.84,177522
35,36,NSE:BEDMUTHA-EQ,104.89,100,₹95.00 - ₹105.00,4.89,2.26,5964
36,37,NSE:GILLANDERS-EQ,104.91,100,₹95.00 - ₹105.00,4.91,-0.09,4202
37,38,NSE:BORORENEW-EQ,475.00,500,₹475.00 - ₹525.00,-5.00,0.06,244086
38,39,NSE:FERMENTA-EQ,475.50,500,₹475.00 - ₹525.00,-4.90,1.04,69810
39,40,NSE:TECHNOCRAF-EQ,475.65,500,₹475.00 - ₹525.00,-4.87,3.97,2956605
40,41,NSE:ICIL-EQ,476.55,500,₹475.00 - ₹525.00,-4.69,6.16,1924680
41,42,NSE:SHAKTIPUMP-EQ,476.80,500,₹475.00 - ₹525.00,-4.64,1.64,331661
42,43,NSE:DYCL-EQ,476.90,500,₹475.00 - ₹525.00,-4.62,5.10,762315
43,44,NSE:KKCL-EQ,477.55,500,₹475.00 - ₹525.00,-4.49,-1.50,15632
44,45,NSE:KIRLFER-EQ,478.10,500,₹475.00 - ₹525.00,-4.38,-0.36,126883
45,46,NSE:POONAWALLA-EQ,478.85,500,₹475.00 - ₹525.00,-4.23,1.47,1880797
46,47,NSE:JKIL-EQ,479.60,500,₹475.00 - ₹525.00,-4.08,0.33,27434
47,48,NSE:PANAMAPET-EQ,480.70,500,₹475.00 - ₹525.00,-3.86,-0.11,164568
48,49,NSE:SMSPHARMA-EQ,482.95,500,₹475.00 - ₹525.00,-3.41,-0.08,801318
49,50,NSE:RAJRATAN-EQ,483.20,500,₹475.00 - ₹525.00,-3.36,7.33,618194
50,51,NSE:JUBLFOOD-EQ,483.30,500,₹475.00 - ₹525.00,-3.34,-1.59,625258
51,52,NSE:ICICIPRULI-EQ,484.50,500,₹475.00 - ₹525.00,-3.10,-0.44,750732
52,53,NSE:HONASA-EQ,484.90,500,₹475.00 - ₹525.00,-3.02,2.38,712921
53,54,NSE:SUPRAJIT-EQ,485.05,500,₹475.00 - ₹525.00,-2.99,0.33,28891
54,55,NSE:PML-EQ,486.00,500,₹475.00 - ₹525.00,-2.80,-2.58,1239
55,56,NSE:POCL-EQ,487.40,500,₹475.00 - ₹525.00,-2.52,3.06,365156
56,57,NSE:GSPCROP-EQ,488.85,500,₹475.00 - ₹525.00,-2.23,0.81,242198
57,58,NSE:TRANSRAILL-EQ,488.90,500,₹475.00 - ₹525.00,-2.22,2.46,10396978
58,59,NSE:ASIANENE-EQ,489.70,500,₹475.00 - ₹525.00,-2.06,0.02,308700
59,60,NSE:RUBYMILLS-EQ,490.20,500,₹475.00 - ₹525.00,-1.96,6.58,111992
60,61,NSE:SUNTV-EQ,490.20,500,₹475.00 - ₹525.00,-1.96,0.02,1771617
61,62,NSE:AARTIIND-EQ,491.35,500,₹475.00 - ₹525.00,-1.73,-0.94,402389
62,63,NSE:SOFTTECH-EQ,491.85,500,₹475.00 - ₹525.00,-1.63,-1.28,3096
63,64,NSE:AGARWALEYE-EQ,494.80,500,₹475.00 - ₹525.00,-1.04,0.35,329131
64,65,NSE:SHREEPUSHK-EQ,495.80,500,₹475.00 - ₹525.00,-0.84,-1.99,50695
65,66,NSE:PRECWIRE-EQ,498.85,500,₹475.00 - ₹525.00,-0.23,1.58,715914
66,67,NSE:HEXT-EQ,500.00,500,₹475.00 - ₹525.00,0.00,-0.83,124075
67,68,NSE:TANLA-EQ,500.40,500,₹475.00 - ₹525.00,0.08,3.10,473046
68,69,NSE:WHBRADY-EQ,502.60,500,₹475.00 - ₹525.00,0.52,8.23,232
69,70,NSE:NEWGEN-EQ,504.15,500,₹475.00 - ₹525.00,0.83,1.70,688103
70,71,NSE:CMLL-EQ,504.65,500,₹475.00 - ₹525.00,0.93,2.80,514379
71,72,NSE:TCIEXP-EQ,505.60,500,₹475.00 - ₹525.00,1.12,4.00,22609
72,73,NSE:BAJAJCON-EQ,505.85,500,₹475.00 - ₹525.00,1.17,-1.54,599193
73,74,NSE:SARDAEN-EQ,505.95,500,₹475.00 - ₹525.00,1.19,0.52,159141
74,75,NSE:BALUFORGE-EQ,506.25,500,₹475.00 - ₹525.00,1.25,0.20,631352
75,76,NSE:SANATHAN-EQ,506.35,500,₹475.00 - ₹525.00,1.27,7.44,484976
76,77,NSE:LANDMARK-EQ,506.40,500,₹475.00 - ₹525.00,1.28,-0.80,57410
77,78,NSE:SAREGAMA-EQ,507.00,500,₹475.00 - ₹525.00,1.40,0.73,438443
78,79,NSE:MAGADSUGAR-EQ,509.20,500,₹475.00 - ₹525.00,1.84,1.69,16374
79,80,NSE:SAIPARENT-EQ,509.30,500,₹475.00 - ₹525.00,1.86,0.52,62456
80,81,NSE:AMRUTANJAN-EQ,510.05,500,₹475.00 - ₹525.00,2.01,2.00,34784
81,82,NSE:WONDERLA-EQ,510.75,500,₹475.00 - ₹525.00,2.15,-0.08,26910
82,83,NSE:ARSSBL-EQ,510.80,500,₹475.00 - ₹525.00,2.16,2.93,413000
83,84,NSE:JKLAKSHMI-EQ,511.20,500,₹475.00 - ₹525.00,2.24,0.67,46467
84,85,NSE:HINDCOPPER-EQ,513.00,500,₹475.00 - ₹525.00,2.60,0.94,6140632
85,86,NSE:SHIVAUM-EQ,513.20,500,₹475.00 - ₹525.00,2.64,-0.36,9201
86,87,NSE:VOEPL-EQ,515.10,500,₹475.00 - ₹525.00,3.02,4.47,79459
87,88,NSE:KLBRENG-B-EQ,518.60,500,₹475.00 - ₹525.00,3.72,-0.17,500546
88,89,NSE:TENNIND-EQ,518.60,500,₹475.00 - ₹525.00,3.72,-2.66,986500
89,90,NSE:AEROFLEX-EQ,520.80,500,₹475.00 - ₹525.00,4.16,0.79,939383
90,91,NSE:JSWENERGY-EQ,521.00,500,₹475.00 - ₹525.00,4.20,0.58,1923195
91,92,NSE:PGEL-EQ,521.15,500,₹475.00 - ₹525.00,4.23,0.18,546381
92,93,NSE:RENTOMOJO-EQ,521.35,500,₹475.00 - ₹525.00,4.27,-0.68,7882264
93,94,NSE:TEJASNET-EQ,521.55,500,₹475.00 - ₹525.00,4.31,1.02,890300
94,95,NSE:APOLLOPIPE-EQ,522.45,500,₹475.00 - ₹525.00,4.49,-0.69,69429
95,96,NSE:JSLL-EQ,524.30,500,₹475.00 - ₹525.00,4.86,1.73,426083
96,97,NSE:JENBURPH-EQ,952.00,1000,₹950.00 - ₹1050.00,-4.80,-0.54,2772
97,98,NSE:INDUSINDBK-EQ,959.30,1000,₹950.00 - ₹1050.00,-4.07,0.45,2626452
98,99,NSE:EXCELINDUS-EQ,963.30,1000,₹950.00 - ₹1050.00,-3.67,1.12,8868
99,100,NSE:CYIENTDLM-EQ,963.50,1000,₹950.00 - ₹1050.00,-3.65,5.05,523966
100,101,NSE:GMBREW-EQ,968.30,1000,₹950.00 - ₹1050.00,-3.17,2.14,49050
101,102,NSE:ASAHIINDIA-EQ,971.30,1000,₹950.00 - ₹1050.00,-2.87,0.64,262585
102,103,NSE:SHARDAMOTR-EQ,971.85,1000,₹950.00 - ₹1050.00,-2.81,-1.41,161127
103,104,NSE:MALLCOM-EQ,975.35,1000,₹950.00 - ₹1050.00,-2.46,2.49,3973
104,105,NSE:JPOLYINVST-EQ,978.95,1000,₹950.00 - ₹1050.00,-2.10,0.64,1063
105,106,NSE:DCMSHRIRAM-EQ,980.00,1000,₹950.00 - ₹1050.00,-2.00,0.07,25367
106,107,NSE:DHANUKA-EQ,982.65,1000,₹950.00 - ₹1050.00,-1.74,1.68,30647
107,108,NSE:MANINDS-EQ,986.70,1000,₹950.00 - ₹1050.00,-1.33,16.10,10691371
108,109,NSE:SPAL-EQ,989.50,1000,₹950.00 - ₹1050.00,-1.05,1.00,26317
109,110,NSE:MIDWESTLTD-EQ,993.40,1000,₹950.00 - ₹1050.00,-0.66,-2.45,29595
110,111,NSE:SBIN-EQ,994.10,1000,₹950.00 - ₹1050.00,-0.59,0.72,4522248
111,112,NSE:TATACONSUM-EQ,994.30,1000,₹950.00 - ₹1050.00,-0.57,1.04,850774
112,113,NSE:GANDHITUBE-EQ,995.05,1000,₹950.00 - ₹1050.00,-0.50,-0.81,27224
113,114,NSE:KSL-EQ,998.25,1000,₹950.00 - ₹1050.00,-0.18,4.08,646949
114,115,NSE:SUPRIYA-EQ,1000.90,1000,₹950.00 - ₹1050.00,0.09,6.58,1007970
115,116,NSE:DHUNINV-EQ,1001.75,1000,₹950.00 - ₹1050.00,0.18,1.85,423
116,117,NSE:HINDALCO-EQ,1003.80,1000,₹950.00 - ₹1050.00,0.38,3.17,5158521
117,118,NSE:TINNARUBR-EQ,1007.25,1000,₹950.00 - ₹1050.00,0.73,-0.08,27984
118,119,NSE:THACKER-EQ,1008.00,1000,₹950.00 - ₹1050.00,0.80,-0.07,18
119,120,NSE:MAITHANALL-EQ,1009.90,1000,₹950.00 - ₹1050.00,0.99,1.50,111790
120,121,NSE:SHRIRAMFIN-EQ,1010.80,1000,₹950.00 - ₹1050.00,1.08,0.48,2916356
121,122,NSE:TECHNOE-EQ,1012.05,1000,₹950.00 - ₹1050.00,1.20,0.64,71021
122,123,NSE:DREDGECORP-EQ,1017.50,1000,₹950.00 - ₹1050.00,1.75,2.38,53819
123,124,NSE:INFY-EQ,1020.50,1000,₹950.00 - ₹1050.00,2.05,-0.86,5108734
124,125,NSE:NELCO-EQ,1020.75,1000,₹950.00 - ₹1050.00,2.08,0.89,511625
125,126,NSE:ABSLAMC-EQ,1026.60,1000,₹950.00 - ₹1050.00,2.66,-0.04,65947
126,127,NSE:SANDESH-EQ,1027.00,1000,₹950.00 - ₹1050.00,2.70,-1.13,644
127,128,NSE:DSSL-EQ,1030.40,1000,₹950.00 - ₹1050.00,3.04,0.80,16469
128,129,NSE:KRISHNADEF-EQ,1032.90,1000,₹950.00 - ₹1050.00,3.29,0.71,66368
129,130,NSE:MANGLMCEM-EQ,1033.30,1000,₹950.00 - ₹1050.00,3.33,2.68,69168
130,131,NSE:BIL-EQ,1034.95,1000,₹950.00 - ₹1050.00,3.50,-1.48,4569
131,132,NSE:GANECOS-EQ,1036.60,1000,₹950.00 - ₹1050.00,3.66,3.83,48904
132,133,NSE:SHILPAMED-EQ,1037.70,1000,₹950.00 - ₹1050.00,3.77,0.44,613628
133,134,NSE:MOTILALOFS-EQ,1042.50,1000,₹950.00 - ₹1050.00,4.25,3.53,2096581
134,135,NSE:BAJFINANCE-EQ,1043.20,1000,₹950.00 - ₹1050.00,4.32,3.41,8618523
135,136,NSE:CCL-EQ,1043.20,1000,₹950.00 - ₹1050.00,4.32,-0.65,235839
136,137,NSE:KSHINTL-EQ,1046.80,1000,₹950.00 - ₹1050.00,4.68,0.56,224075
137,138,NSE:DODLA-EQ,1048.60,1000,₹950.00 - ₹1050.00,4.86,0.10,19425
138,139,NSE:NH-EQ,1919.30,2000,₹1900.00 - ₹2100.00,-4.04,1.91,104223
139,140,NSE:ECLERX-EQ,1924.20,2000,₹1900.00 - ₹2100.00,-3.79,0.01,60071
140,141,NSE:LALPATHLAB-EQ,1924.30,2000,₹1900.00 - ₹2100.00,-3.79,0.76,230347
141,142,NSE:FIEMIND-EQ,1924.50,2000,₹1900.00 - ₹2100.00,-3.78,0.93,67467
142,143,NSE:MANORAMA-EQ,1929.40,2000,₹1900.00 - ₹2100.00,-3.53,0.96,141711
143,144,NSE:HONDAPOWER-EQ,1931.70,2000,₹1900.00 - ₹2100.00,-3.41,0.79,1632
144,145,NSE:IKS-EQ,1937.80,2000,₹1900.00 - ₹2100.00,-3.11,3.67,1011998
145,146,NSE:AXISCADES-EQ,1940.20,2000,₹1900.00 - ₹2100.00,-2.99,2.60,291136
146,147,NSE:NBIFIN-EQ,1948.90,2000,₹1900.00 - ₹2100.00,-2.55,0.05,5488
147,148,NSE:HINDUNILVR-EQ,1950.00,2000,₹1900.00 - ₹2100.00,-2.50,0.84,870342
148,149,NSE:COROMANDEL-EQ,1956.00,2000,₹1900.00 - ₹2100.00,-2.20,0.57,144853
149,150,NSE:IPCALAB-EQ,1962.60,2000,₹1900.00 - ₹2100.00,-1.87,-1.50,159445
150,151,NSE:ARMANFIN-EQ,1968.90,2000,₹1900.00 - ₹2100.00,-1.55,-0.30,12730
151,152,NSE:ADVAIT-EQ,1976.80,2000,₹1900.00 - ₹2100.00,-1.16,-1.44,35052
152,153,NSE:GRINDWELL-EQ,1977.60,2000,₹1900.00 - ₹2100.00,-1.12,1.84,22292
153,154,NSE:EMCURE-EQ,1981.70,2000,₹1900.00 - ₹2100.00,-0.91,0.34,37562
154,155,NSE:PHOENIXLTD-EQ,1993.20,2000,₹1900.00 - ₹2100.00,-0.34,2.04,639296
155,156,NSE:GRPLTD-EQ,2001.20,2000,₹1900.00 - ₹2100.00,0.06,0.06,244
156,157,NSE:GODFRYPHLP-EQ,2003.00,2000,₹1900.00 - ₹2100.00,0.15,1.68,144961
157,158,NSE:BHARATFORG-EQ,2004.00,2000,₹1900.00 - ₹2100.00,0.20,-0.25,759299
158,159,NSE:NOVARTIND-EQ,2027.40,2000,₹1900.00 - ₹2100.00,1.37,2.74,77712
159,160,NSE:LAURUSLABS-EQ,2034.00,2000,₹1900.00 - ₹2100.00,1.70,1.37,1363988
160,161,NSE:LUMAXTECH-EQ,2044.90,2000,₹1900.00 - ₹2100.00,2.25,-3.38,280450
161,162,NSE:WABAG-EQ,2048.70,2000,₹1900.00 - ₹2100.00,2.43,-1.13,380343
162,163,NSE:MACPOWER-EQ,2059.50,2000,₹1900.00 - ₹2100.00,2.97,-1.76,43775
163,164,NSE:TEGA-EQ,2078.80,2000,₹1900.00 - ₹2100.00,3.94,0.47,671454
164,165,NSE:TCS-EQ,2089.60,2000,₹1900.00 - ₹2100.00,4.48,-0.73,2228402
165,166,NSE:HYUNDAI-EQ,2095.00,2000,₹1900.00 - ₹2100.00,4.75,-0.29,358724
166,167,NSE:BEML-EQ,2095.40,2000,₹1900.00 - ₹2100.00,4.77,-0.07,204095
167,168,NSE:HAPPYFORGE-EQ,2099.80,2000,₹1900.00 - ₹2100.00,4.99,-0.41,82497

CSV saved successfully:
/home/manish/trading_project/stock_screener/notebooks/price_scanner_results.csv

In [11]:
# ==========================================
# CELL 8 — ABOVE PRICE LEVEL 10% SCANNER
#          + SAVE CSV
# ==========================================

PRICE_LEVELS = [100,200,300,500,1000,2000]
RANGE_PERCENT = 5.0

scanner_results = []

for reference_price in PRICE_LEVELS:

    lower_price = reference_price
    upper_price = reference_price * (1 + RANGE_PERCENT / 100)

    matches = quote_df[
        (quote_df["LTP"] >= lower_price) &
        (quote_df["LTP"] <= upper_price)
    ].copy()

    if not matches.empty:

        matches["Reference"] = reference_price

        matches["Range"] = (
            f"₹{lower_price:.2f} - ₹{upper_price:.2f}"
        )

        matches["Distance (%)"] = (
            (matches["LTP"] - reference_price)
            / reference_price
            * 100
        ).round(2)

        scanner_results.append(matches)


if scanner_results:

    price_scanner_df = pd.concat(
        scanner_results,
        ignore_index=True
    )

    price_scanner_df = price_scanner_df[
        [
            "Symbol",
            "LTP",
            "Reference",
            "Range",
            "Distance (%)",
            "Change (%)",
            "Volume"
        ]
    ]

    price_scanner_df = price_scanner_df.sort_values(
        ["Reference", "Distance (%)"],
        ascending=[True, True]
    ).reset_index(drop=True)

    price_scanner_df.insert(
        0,
        "No.",
        range(1, len(price_scanner_df) + 1)
    )

    pd.set_option("display.max_rows", None)
    pd.set_option("display.max_columns", None)

    print(
        f"Stocks above reference levels "
        f"within {RANGE_PERCENT}%: "
        f"{len(price_scanner_df)}"
    )

    display(price_scanner_df)

    # --------------------------------------
    # SAVE CSV
    # --------------------------------------

    CSV_PATH = (
        PROJECT_DIR
        / "notebooks"
        / "above_price_scanner_results.csv"
    )

    price_scanner_df.to_csv(
        CSV_PATH,
        index=False
    )

    print("\nCSV saved successfully:")
    print(CSV_PATH)

else:

    print("No stocks found above the selected price levels.")

Stocks above reference levels within 5.0%: 119

,No.,Symbol,LTP,Reference,Range,Distance (%),Change (%),Volume
0,1,NSE:INDORAMA-EQ,100.00,100,₹100.00 - ₹105.00,0.00,-3.45,1969705
1,2,NSE:SARLAPOLY-EQ,100.03,100,₹100.00 - ₹105.00,0.03,0.78,66846
2,3,NSE:ANSALBU-EQ,100.14,100,₹100.00 - ₹105.00,0.14,11.12,179538
3,4,NSE:ENIL-EQ,100.17,100,₹100.00 - ₹105.00,0.17,0.53,2106
4,5,NSE:JKIPL-EQ,100.25,100,₹100.00 - ₹105.00,0.25,1.02,3606
5,6,NSE:MAHEPC-EQ,100.45,100,₹100.00 - ₹105.00,0.45,1.72,18962
6,7,NSE:ATLASCYCLE-EQ,100.46,100,₹100.00 - ₹105.00,0.46,7.39,239595
7,8,NSE:DBREALTY-EQ,101.48,100,₹100.00 - ₹105.00,1.48,5.00,1033102
8,9,NSE:ALKALI-EQ,101.63,100,₹100.00 - ₹105.00,1.63,-1.52,169113
9,10,NSE:SAMBANDAM-EQ,102.50,100,₹100.00 - ₹105.00,2.50,1.49,1229
10,11,NSE:AAREYDRUGS-EQ,102.63,100,₹100.00 - ₹105.00,2.63,0.11,352115
11,12,NSE:CSM-EQ,103.93,100,₹100.00 - ₹105.00,3.93,-1.16,288893
12,13,NSE:MAANALU-EQ,103.93,100,₹100.00 - ₹105.00,3.93,-0.84,177522
13,14,NSE:BEDMUTHA-EQ,104.89,100,₹100.00 - ₹105.00,4.89,2.26,5964
14,15,NSE:GILLANDERS-EQ,104.91,100,₹100.00 - ₹105.00,4.91,-0.09,4202
15,16,NSE:MHRIL-EQ,201.39,200,₹200.00 - ₹210.00,0.69,1.17,137743
16,17,NSE:RALLIS-EQ,202.62,200,₹200.00 - ₹210.00,1.31,0.33,285026
17,18,NSE:MOBIKWIK-EQ,202.93,200,₹200.00 - ₹210.00,1.47,-2.91,1411387
18,19,NSE:EIEL-EQ,203.32,200,₹200.00 - ₹210.00,1.66,1.12,442187
19,20,NSE:ABCOTS-EQ,203.57,200,₹200.00 - ₹210.00,1.78,-0.82,755
20,21,NSE:RITES-EQ,204.05,200,₹200.00 - ₹210.00,2.03,0.22,433416
21,22,NSE:AFSL-EQ,204.56,200,₹200.00 - ₹210.00,2.28,1.77,7352
22,23,NSE:ADANIPOWER-EQ,204.80,200,₹200.00 - ₹210.00,2.40,-1.04,20269523
23,24,NSE:UDS-EQ,205.27,200,₹200.00 - ₹210.00,2.64,3.60,135877
24,25,NSE:ALLTIME-EQ,205.36,200,₹200.00 - ₹210.00,2.68,0.80,34329
25,26,NSE:SPARC-EQ,205.65,200,₹200.00 - ₹210.00,2.83,3.88,1935408
26,27,NSE:AEROPLANE-EQ,205.74,200,₹200.00 - ₹210.00,2.87,0.46,661546
27,28,NSE:GREAVESCOT-EQ,206.01,200,₹200.00 - ₹210.00,3.00,3.18,2224825
28,29,NSE:NOCIL-EQ,206.30,200,₹200.00 - ₹210.00,3.15,6.40,7384798
29,30,NSE:IOLCP-EQ,206.60,200,₹200.00 - ₹210.00,3.30,3.10,3474298
30,31,NSE:BNAGROCHEM-EQ,206.88,200,₹200.00 - ₹210.00,3.44,3.00,1181
31,32,NSE:MOSCHIP-EQ,207.32,200,₹200.00 - ₹210.00,3.66,-0.02,808871
32,33,NSE:IKIO-EQ,207.89,200,₹200.00 - ₹210.00,3.94,0.93,188483
33,34,NSE:INDIANCARD-EQ,208.64,200,₹200.00 - ₹210.00,4.32,-2.02,1719
34,35,NSE:VSTIND-EQ,208.80,200,₹200.00 - ₹210.00,4.40,1.51,162276
35,36,NSE:VAIBHAVGBL-EQ,209.49,200,₹200.00 - ₹210.00,4.75,0.63,196618
36,37,NSE:OMAXAUTO-EQ,209.94,200,₹200.00 - ₹210.00,4.97,10.00,199826
37,38,NSE:ANGELONE-EQ,300.00,300,₹300.00 - ₹315.00,0.00,1.66,2026293
38,39,NSE:SWANCORP-EQ,300.05,300,₹300.00 - ₹315.00,0.02,-0.89,775263
39,40,NSE:TMPV-EQ,300.50,300,₹300.00 - ₹315.00,0.17,0.15,4683895
40,41,NSE:EIHOTEL-EQ,301.15,300,₹300.00 - ₹315.00,0.38,-0.90,98871
41,42,NSE:REPRO-EQ,301.35,300,₹300.00 - ₹315.00,0.45,1.06,15927
42,43,NSE:AEGISVOPAK-EQ,302.80,300,₹300.00 - ₹315.00,0.93,0.46,1254083
43,44,NSE:JAINREC-EQ,302.95,300,₹300.00 - ₹315.00,0.98,4.02,5175026
44,45,NSE:ENGINERSIN-EQ,306.20,300,₹300.00 - ₹315.00,2.07,1.21,11229270
45,46,NSE:ONIXSOLAR-EQ,306.50,300,₹300.00 - ₹315.00,2.17,-4.99,17334
46,47,NSE:GENUSPOWER-EQ,308.35,300,₹300.00 - ₹315.00,2.78,-0.36,967695
47,48,NSE:ROHLTD-EQ,309.75,300,₹300.00 - ₹315.00,3.25,1.23,25196
48,49,NSE:LTF-EQ,310.00,300,₹300.00 - ₹315.00,3.33,1.67,5926308
49,50,NSE:RECLTD-EQ,311.50,300,₹300.00 - ₹315.00,3.83,1.43,5448840
50,51,NSE:NORTHARC-EQ,313.80,300,₹300.00 - ₹315.00,4.60,-0.66,587471
51,52,NSE:TIPSFILMS-EQ,314.75,300,₹300.00 - ₹315.00,4.92,-0.51,2164
52,53,NSE:HEXT-EQ,500.00,500,₹500.00 - ₹525.00,0.00,-0.83,124075
53,54,NSE:TANLA-EQ,500.40,500,₹500.00 - ₹525.00,0.08,3.10,473046
54,55,NSE:WHBRADY-EQ,502.60,500,₹500.00 - ₹525.00,0.52,8.23,232
55,56,NSE:NEWGEN-EQ,504.15,500,₹500.00 - ₹525.00,0.83,1.70,688103
56,57,NSE:CMLL-EQ,504.65,500,₹500.00 - ₹525.00,0.93,2.80,514379
57,58,NSE:TCIEXP-EQ,505.60,500,₹500.00 - ₹525.00,1.12,4.00,22609
58,59,NSE:BAJAJCON-EQ,505.85,500,₹500.00 - ₹525.00,1.17,-1.54,599193
59,60,NSE:SARDAEN-EQ,505.95,500,₹500.00 - ₹525.00,1.19,0.52,159141
60,61,NSE:BALUFORGE-EQ,506.25,500,₹500.00 - ₹525.00,1.25,0.20,631352
61,62,NSE:SANATHAN-EQ,506.35,500,₹500.00 - ₹525.00,1.27,7.44,484976
62,63,NSE:LANDMARK-EQ,506.40,500,₹500.00 - ₹525.00,1.28,-0.80,57410
63,64,NSE:SAREGAMA-EQ,507.00,500,₹500.00 - ₹525.00,1.40,0.73,438443
64,65,NSE:MAGADSUGAR-EQ,509.20,500,₹500.00 - ₹525.00,1.84,1.69,16374
65,66,NSE:SAIPARENT-EQ,509.30,500,₹500.00 - ₹525.00,1.86,0.52,62456
66,67,NSE:AMRUTANJAN-EQ,510.05,500,₹500.00 - ₹525.00,2.01,2.00,34784
67,68,NSE:WONDERLA-EQ,510.75,500,₹500.00 - ₹525.00,2.15,-0.08,26910
68,69,NSE:ARSSBL-EQ,510.80,500,₹500.00 - ₹525.00,2.16,2.93,413000
69,70,NSE:JKLAKSHMI-EQ,511.20,500,₹500.00 - ₹525.00,2.24,0.67,46467
70,71,NSE:HINDCOPPER-EQ,513.00,500,₹500.00 - ₹525.00,2.60,0.94,6140632
71,72,NSE:SHIVAUM-EQ,513.20,500,₹500.00 - ₹525.00,2.64,-0.36,9201
72,73,NSE:VOEPL-EQ,515.10,500,₹500.00 - ₹525.00,3.02,4.47,79459
73,74,NSE:KLBRENG-B-EQ,518.60,500,₹500.00 - ₹525.00,3.72,-0.17,500546
74,75,NSE:TENNIND-EQ,518.60,500,₹500.00 - ₹525.00,3.72,-2.66,986500
75,76,NSE:AEROFLEX-EQ,520.80,500,₹500.00 - ₹525.00,4.16,0.79,939383
76,77,NSE:JSWENERGY-EQ,521.00,500,₹500.00 - ₹525.00,4.20,0.58,1923195
77,78,NSE:PGEL-EQ,521.15,500,₹500.00 - ₹525.00,4.23,0.18,546381
78,79,NSE:RENTOMOJO-EQ,521.35,500,₹500.00 - ₹525.00,4.27,-0.68,7882264
79,80,NSE:TEJASNET-EQ,521.55,500,₹500.00 - ₹525.00,4.31,1.02,890300
80,81,NSE:APOLLOPIPE-EQ,522.45,500,₹500.00 - ₹525.00,4.49,-0.69,69429
81,82,NSE:JSLL-EQ,524.30,500,₹500.00 - ₹525.00,4.86,1.73,426083
82,83,NSE:SUPRIYA-EQ,1000.90,1000,₹1000.00 - ₹1050.00,0.09,6.58,1007970
83,84,NSE:DHUNINV-EQ,1001.75,1000,₹1000.00 - ₹1050.00,0.18,1.85,423
84,85,NSE:HINDALCO-EQ,1003.80,1000,₹1000.00 - ₹1050.00,0.38,3.17,5158521
85,86,NSE:TINNARUBR-EQ,1007.25,1000,₹1000.00 - ₹1050.00,0.73,-0.08,27984
86,87,NSE:THACKER-EQ,1008.00,1000,₹1000.00 - ₹1050.00,0.80,-0.07,18
87,88,NSE:MAITHANALL-EQ,1009.90,1000,₹1000.00 - ₹1050.00,0.99,1.50,111790
88,89,NSE:SHRIRAMFIN-EQ,1010.80,1000,₹1000.00 - ₹1050.00,1.08,0.48,2916356
89,90,NSE:TECHNOE-EQ,1012.05,1000,₹1000.00 - ₹1050.00,1.20,0.64,71021
90,91,NSE:DREDGECORP-EQ,1017.50,1000,₹1000.00 - ₹1050.00,1.75,2.38,53819
91,92,NSE:INFY-EQ,1020.50,1000,₹1000.00 - ₹1050.00,2.05,-0.86,5108734
92,93,NSE:NELCO-EQ,1020.75,1000,₹1000.00 - ₹1050.00,2.08,0.89,511625
93,94,NSE:ABSLAMC-EQ,1026.60,1000,₹1000.00 - ₹1050.00,2.66,-0.04,65947
94,95,NSE:SANDESH-EQ,1027.00,1000,₹1000.00 - ₹1050.00,2.70,-1.13,644
95,96,NSE:DSSL-EQ,1030.40,1000,₹1000.00 - ₹1050.00,3.04,0.80,16469
96,97,NSE:KRISHNADEF-EQ,1032.90,1000,₹1000.00 - ₹1050.00,3.29,0.71,66368
97,98,NSE:MANGLMCEM-EQ,1033.30,1000,₹1000.00 - ₹1050.00,3.33,2.68,69168
98,99,NSE:BIL-EQ,1034.95,1000,₹1000.00 - ₹1050.00,3.50,-1.48,4569
99,100,NSE:GANECOS-EQ,1036.60,1000,₹1000.00 - ₹1050.00,3.66,3.83,48904
100,101,NSE:SHILPAMED-EQ,1037.70,1000,₹1000.00 - ₹1050.00,3.77,0.44,613628
101,102,NSE:MOTILALOFS-EQ,1042.50,1000,₹1000.00 - ₹1050.00,4.25,3.53,2096581
102,103,NSE:BAJFINANCE-EQ,1043.20,1000,₹1000.00 - ₹1050.00,4.32,3.41,8618523
103,104,NSE:CCL-EQ,1043.20,1000,₹1000.00 - ₹1050.00,4.32,-0.65,235839
104,105,NSE:KSHINTL-EQ,1046.80,1000,₹1000.00 - ₹1050.00,4.68,0.56,224075
105,106,NSE:DODLA-EQ,1048.60,1000,₹1000.00 - ₹1050.00,4.86,0.10,19425
106,107,NSE:GRPLTD-EQ,2001.20,2000,₹2000.00 - ₹2100.00,0.06,0.06,244
107,108,NSE:GODFRYPHLP-EQ,2003.00,2000,₹2000.00 - ₹2100.00,0.15,1.68,144961
108,109,NSE:BHARATFORG-EQ,2004.00,2000,₹2000.00 - ₹2100.00,0.20,-0.25,759299
109,110,NSE:NOVARTIND-EQ,2027.40,2000,₹2000.00 - ₹2100.00,1.37,2.74,77712
110,111,NSE:LAURUSLABS-EQ,2034.00,2000,₹2000.00 - ₹2100.00,1.70,1.37,1363988
111,112,NSE:LUMAXTECH-EQ,2044.90,2000,₹2000.00 - ₹2100.00,2.25,-3.38,280450
112,113,NSE:WABAG-EQ,2048.70,2000,₹2000.00 - ₹2100.00,2.43,-1.13,380343
113,114,NSE:MACPOWER-EQ,2059.50,2000,₹2000.00 - ₹2100.00,2.97,-1.76,43775
114,115,NSE:TEGA-EQ,2078.80,2000,₹2000.00 - ₹2100.00,3.94,0.47,671454
115,116,NSE:TCS-EQ,2089.60,2000,₹2000.00 - ₹2100.00,4.48,-0.73,2228402
116,117,NSE:HYUNDAI-EQ,2095.00,2000,₹2000.00 - ₹2100.00,4.75,-0.29,358724
117,118,NSE:BEML-EQ,2095.40,2000,₹2000.00 - ₹2100.00,4.77,-0.07,204095
118,119,NSE:HAPPYFORGE-EQ,2099.80,2000,₹2000.00 - ₹2100.00,4.99,-0.41,82497

CSV saved successfully:
/home/manish/trading_project/stock_screener/notebooks/above_price_scanner_results.csv